name: 'Gitleaks Custom Scan'
description: 'Build and run Gitleaks with custom rules'
inputs:
  workspace:
    description: 'GitHub workspace path'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        git clone --branch dockerwithrules https://github.com/PoorneshORG/SecretScan.git secret-scan
        docker build -t gitleaks-custom -f secret-scan/Dockerfile secret-scan
        docker run --rm \
          -v "${{ inputs.workspace }}:/app" \
          -w /app \
          gitleaks-custom detect \
            --source=/app \
            --config=/app/secret-scan/rules.toml \
            --no-git \
            --verbose \
            --exit-code 1 || true
      shell: bash
