name: SecurityPipeline

jobs:
  secret-scan:
    name: Gitleaks-proxy
    runs-on: ubuntu-latest

    steps:

      - name: Clone SecretScan repo (Dockerfile + rules)
        run: |
          git clone --branch dockerwithrules https://github.com/PoorneshORG/SecretScan.git secret-scan

      - name: Build Gitleaks Docker image with custom rules
        run: |
          docker build -t gitleaks-custom -f secret-scan/Dockerfile secret-scan

      - name: Run Gitleaks - custom rules
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            gitleaks-custom detect \
              --source=/app \
              --config=/app/secret-scan/rules.toml \
              --no-git \
              --verbose \
              --exit-code 1 || true