name: SecurityPipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Gitleaks Custom Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repo-B (the code you want to scan)
      - name: Checkout source code (Repo-B)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Clone PoorneshORG/horusec repo to get Dockerfile and rules.toml
      - name: Clone horusec repo for Dockerfile and rules
        run: |
          git clone --branch TESTING https://github.com/PoorneshORG/horusec.git gitleaks

      # Step 3: Build the custom Gitleaks Docker image
      - name: Build custom Gitleaks image
        run: |
          docker build -t gitleaks-custom -f gitleaks/Dockerfile gitleaks

      # Step 4: Run Gitleaks with custom rules on Repo-B
      - name: Run Gitleaks scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            gitleaks-custom detect \
              --source=/app \
              --config=/app/gitleaks/rules.toml \
              --no-git \
              --verbose \
              --exit-code 1
